<?php

/**
 * @file
 * Contains azure_appinsights.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function azure_appinsights_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the azure_appinsights module.
    case 'help.page.azure_appinsights':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add Azure app insights tracking code.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function azure_appinsights_page_attachments(array &$page) {
  // Conditionally attach an asset to the page.
  if (\Drupal::currentUser()->isAnonymous()) {

    $config = \Drupal::config('azure_appinsights.settings');
    $instrumentation_key = $config->get('instrumentation_key');

    if (!empty($instrumentation_key)) {
      $page['#attached']['library'][] = 'azure_appinsights/azure_appinsights';
      $page['#attached']['drupalSettings']['azure_appinsights']['instrumentationKey'] = Html::escape($instrumentation_key);
    }
  }
}
