_core:
  default_config_hash: QDFjOXYIYVwCPQYHY4wAx4DUqOEkNaZokIx6DGApR9I
langcode: pt-br
enable_globally: 1
enable_globally_on_admin_routes: false
default_challenge: recaptcha_v3/contato
description: 'Esta questão é para verificar se você é ou não um visitante humano e prevenir submissões automáticas de spam.'
title: CAPTCHA
administration_mode: false
administration_mode_on_admin_routes: false
whitelist_ips: ''
wrong_captcha_response_message: 'A sua resposta para o CAPTCHA não foi correta.'
default_validation: 0
persistence: 1
enable_stats: true
log_wrong_responses: false
