_core:
  default_config_hash: TgDhjkaZTZ249_U2CFEd--I4RLMZDmPWSO8pmr3odzw
entity_types:
  node: node
  user: user
  menu_link_content: menu_link_content
  block_content: 0
  comment: 0
  shortcut: 0
  taxonomy_term: 0
  webform_submission: 0
langcode: pt-br
