cron_last_run: 1702903156
cron_frequency: 604800
use_time_interval: false
time_interval_start: '01:30'
time_interval_end: '02:30'
all_tables: 1
write_log: 0
_core:
  default_config_hash: T_ds3REH4r3NJRKBQ8cLc-RVnb4uooa-F_oEyWxdB8w
langcode: pt-br
table_list_casafirjancityco_casafirjanprod: {  }
actions: null
form_build_id: form-JCU3jxf-4g4UMEyyJLE17gMHgx2jMbsoQG5k1ZAK8tk
form_token: k-deoGHSaVw450-PhpYYCSaLdECfwYc7ET3rHTAnZro
form_id: db_maintenance_admin_settings
