_core:
  default_config_hash: ttd8HXcqwSjGgp-fWA3gUA8q4TNvXB0a72pkFlnF56g
langcode: pt-br
hotlink: true
origin: 'http://casafirjan.com.br'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
excluded_extensions: ''
