<?php

/**
 * @file
 * Provides a city connect import log entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function city_connect_import_log_theme() {
  return [
    'city_connect_import_log' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for city connect import log templates.
 *
 * Default template: city-connect-import-log.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the city connect import log information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_city_connect_import_log(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

